### ISSUE TITLE
Give the docs more air

### ISSUE THREAD

**Issue by vladshcherbin** [jagi/meteor-astronomy-docs#13]
Now, the documentation feels a bit heavy and endless with scrolling. I know, it took you time and ideas to create all of this, but maybe make it more airy and spacious? I propose to show only first level section headers in the sidebar and to divide the docs into pages with links and more white space.

For example, [docs](http://laravel.com/docs) - very clear, airy and fresh. Only main sections in the sidebar.

Now go to [ORM](http://laravel.com/docs/5.1/eloquent) - there is a table of contents with all sub-sections. Also very airy and has lots of white space.

What do you think?

**Comment by lukejagodzinski** [comment]
Yes it's a problem that it's too long, especially on mobile, when it has problems with scrolling. It may be also a problem with progress bar of scrolling however it would definitely need separating into some sections on different pages. However, as I'm busy with other work right now I have to postpone it. Can't do all the things at once :).

If it goes about example documentation page you mentioned, I think it's still a little bit complex. What I don't like about it, is that I don't see where I am in the tree of sections.

When redesigning documentation page I would have to decide how deep the tree can be. Right now it's up to 3 levels deep, not including the 0 level. I would have to separate it into bigger sections. But I don't know how would it feel reading.

Ok as I said I know it needs improvements but I have to postpone it :) Forgive me :)

**Comment by vladshcherbin** [comment]
Sure @jagi , don't worry about the docs, they are great, just a little bit messy and complex for a newcomer. Update when you'll have free time and mood for them ;)

**Comment by lukejagodzinski** [comment]
Sure :-). Thanks for your help with promoting Astronomy :-)
